### ISSUE TITLE
Lag issues.

### ISSUE THREAD

**Issue by cationsk** [BitLimit/PvP#12]
At the time of writing there are some pretty game-breaking lag issues going on. The two most noticable ones were:
- Very slow world loading.
- Misplaced player hitbox: A player can get hit when his opponent attacks the hitbox of where the player was more than one second ago.

**Comment by kolinkrewinkel** [comment]
Probably your internet.

**Comment by cationsk** [comment]
Nope, did a speed- and pingtest before I reported.

Ping: 53ms
Speed: up: 1.24Mb/s, Down: 5.31Mb/s

**Comment by kolinkrewinkel** [comment]
That could very well do it.  I'm on a 50/30 connection and never notice any lag.  May want to take it up with Coe if it's that kind of issue, it's inherent with the game.

**Comment by cationsk** [comment]
Fair enough, I'll just close this issue then for not being a real issue :P

**Comment by kolinkrewinkel** [comment]
Hehe. :)
