### ISSUE TITLE
Respawn at place of death after logging out after respawning.

### ISSUE THREAD

**Issue by cationsk** [BitLimit/PvP#7]
Once a player dies they are able to respawn at the place of death.

To reproduce: 
- Die or get killed
- Respawn
- Log out and log back in.

**Comment by kolinkrewinkel** [comment]
Hmm, okay.  I'll look into this, as it's happened to me now too.  Thanks. :)

**Comment by kolinkrewinkel** [comment]
Fixed with random respawns.  Closing.
